name: KitchenSink
version: 0.7.1
author: Travis Watkins
main: nu.nerd.kitchensink.KitchenSink
softdepend: [WorldGuard, bPermissions]
permissions:
    kitchensink.*:
        description: Access to all KitchenSink commands
        children:
            kitchensink.admin: true
            kitchensink.list: true
            kitchensink.lag: true
            kitchensink.unenchant: true
            kitchensink.ksinventory: true
            kitchensink.petadmin: true
            kitchensink.mobcount: true
            kitchensink.pingserver: true
            kitchensink.countdown: true
    kitchensink.admin:
        description: A marker permission that signifies that the player has Admin privileges of various kinds.
        default: op
        children:
            kitchensink.pingserver: true
    kitchensink.list:
        description: List online players
        default: true
    kitchensink.lag:
        description: Show lag stats
        default: op
    kitchensink.unenchant:
        description: Remove enchants from current item
        default: op
    kitchensink.ksinventory:
        description: Edit a players inventory
        default: op
    kitchensink.petadmin:
        description: Bypass ownership test in /unlock-horse, /lock-horse and /untame.
        default: op
    kitchensink.mobcount:
        default: op
    kitchensink.pingserver:
        default: op
    kitchensink.countdown:
        description: Allows access to /countdown, /cdcancel, and /cdconfig.
        default: op
description: 

commands:
    unenchant:
        description: Remove enchants from current item
        permission: kitchensink.unenchant
    lag:
        description: Get current TPS and memory stats
    list:
        description: List currently online players
        permission: kitchensink.list
        usage: |
           /list: Show online players
    ksinventory:
        description: Edit a players inventory
        permission: kitchensink.ksinventory
        usage: |
           /ksinventory <player> [clear]: Edit a players inventory
    painting:
        description: Allows selection of the next painting placed.
        usage: |
            /painting [<name>]: Choose the painting you will place next.
    prain:
        description: Turns client-side weather on or off.
        usage: |
            /prain [on|off]
    nextrestart:
        description: Gives you the amount of time until the next restart
    lock-horse:
        description: Lock a horse so that only the owner can ride it.
        usage: |
            /lock-horse: Lock the next horse owned by you that you right click on.
    unlock-horse:
        description: Unlock a horse so that players other than the owner can ride it.
        usage: |
            /unlock-horse: Unlock the next horse owned by you that you right click on.
    untame:
        description: Untame a pet that you own.
        usage: |
            /untame: Untame the next pet owned by you that you right click on.
    allow-portal:
        description: An admin can bypass the safe-portals check by looking at the frame of a portal (excluding the corners) and running this command before lighting the portal.
        permission: kitchensink.admin
        usage: |
            /<command>: Look at a portal frame and run this before lighting it to bypass safe portals protections. 
    mob-count:
        description: Get a count of all loaded mobs
        permission: kitchensink.admin
        usage: |
            /mob-count: Get a count of all loaded mobs
    enchant-book:        
        description: Enchant the book(s) in your hand with the specified enchantment.
        permission: kitchensink.admin
        usage: |
            /<command> <enchantment> <level>: Enchant the held book(s) with the specified enchantment.
    ping-server:
        description: Pings another minecraft server and displays returned information
        permission: kitchensink.pingserver
        usage: |
            /ping-server <server[:port]> [parameter]
    countdown:
        description: Runs a countdown from the specified time and displays message when done.
        permission: kitchensink.countdown
        usage: |
            /countdown [<seconds>:10] [<message>:"Go!"]
    cdcancel:
        description: Cancels the currently running countdown.
        permission: kitchensink.countdown
        usage: |
            /cdcancel
    cdconfig:
        description: Configure the countdown time limit, format, colors, and styles.
        permission: kitchenskin.countdown
        usage: |
            /cdconfig <maxTime seconds>|<format __$s__>|<color &a-&f>|<style &m-&r>|<msgColor &a-&f>|<msgStyle &m-&r> 
