name: KitchenSink
version: 0.3
author: Travis Watkins
main: nu.nerd.kitchensink.KitchenSink
softdepend: [WorldGuard]
permissions:
    kitchensink.list:
        description: List online players
        default: true
    kitchensink.lag:
        description: Show lag stats
        default: op
    kitchensink.unenchant:
        description: Remove enchants from current item
        default: op
    kitchensink.ksinventory:
        description: Edit a players inventory
        default: op
description: 

commands:
    unenchant:
        description: Remove enchants from current item
        permission: kitchensink.unenchant
    lag:
        description: Get current TPS and memory stats
    list:
        description: List currently online players
        permission: kitchensink.list
        usage: |
           /list: Show online players
    ksinventory:
        description: Edit a players inventory
        permission: kitchensink.ksinventory
        usage: |
           /ksinventory <player> [clear]: Edit a players inventory
    painting:
        description: Allows selection of the next painting placed.
        usage: |
            /painting [<name>]: Choose the painting you will place next.
    nextrestart:
        description: Gives you the amount of time until the next restart
