name: KitchenSink
version: ${project.version}
author: [Travis Watkins, PPGOME]
main: nu.nerd.kitchensink.KitchenSink
softdepend: [WorldGuard, LuckPerms, LogBlock, ProtocolLib]
description: Miscellaneous tweaks and fixes for Spigot servers.
api-version: 1.13

permissions:
    kitchensink.*:
        description: Access to all KitchenSink commands
        children:
            kitchensink.admin: true
            kitchensink.unenchant: true
            kitchensink.countdown: true
    kitchensink.admin:
        description: A marker permission that signifies that the player has Admin privileges of various kinds.
        default: op
        children:
            kitchensink.pingserver: true
    kitchensink.unenchant:
        description: Remove enchants from current item
        default: op
    kitchensink.ksinventory:
        description: Edit a players inventory
        default: op
    kitchensink.mobcount:
        default: op
    kitchensink.countdown:
        description: Allows access to /countdown, /cdcancel, and /cdconfig.
        default: op
    kitchensink.noteblocks:
        description: Allows use of /note
        default: true

commands:
    ksreload:
        description: Reloads the config from file to pull in updates.
        permission: kitchensink.admin
    unenchant:
        description: Remove enchants from current item
        permission: kitchensink.unenchant
    trace:
        description: idk rn
        permission: kitchensink.trace
    xray-top:
        description: idk rn
        permission: kitchensink.xraytop
    painting:
        description: Allows selection of the next painting placed.
        usage: |
            /painting [<name>]: Choose the painting you will place next.
    nextrestart:
        description: Gives you the amount of time until the next restart
    allow-portal:
        description: An admin can bypass the safe-portals check by looking at the frame of a portal (excluding the corners) and running this command before lighting the portal.
        permission: kitchensink.admin
        usage: |
            /<command>: Look at a portal frame and run this before lighting it to bypass safe portals protections.
    enchant-book:        
        description: Enchant the book(s) in your hand with the specified enchantment.
        permission: kitchensink.admin
        usage: |
            /<command> <enchantment> <level>: Enchant the held book(s) with the specified enchantment.
    countdown:
        description: Runs a countdown from the specified time and displays message when done.
        permission: kitchensink.countdown
        usage: |
            /countdown [<seconds>:10] [<message>:"Go!"]
    cdcancel:
        description: Cancels the currently running countdown.
        permission: kitchensink.countdown
        usage: |
            /cdcancel
    cdconfig:
        description: Configure the countdown time limit, format, colors, and styles.
        permission: kitchenskin.countdown
        usage: |
            /cdconfig <maxTime seconds>|<format __$s__>|<color &a-&f>|<style &m-&r>|<msgColor &a-&f>|<msgStyle &m-&r> 
    note:
        description: Change the note a noteblock plays.
        permission: kitchensink.noteblocks
        usage: |
            /note <note>[#/b] [high]
